---
server:
  port: 8081
  address: localhost
  servlet:
    context-path: /
---
modules:
  frontend:
    filepath: file:D:\\development\\temporary\\pretty-admin-template\\frontend\\node_modules\\gentelella\\
---
